name: Update Historical Matching Aspects

on:
  schedule:
    - cron: "0 0 * * *"  # This triggers the workflow at midnight UTC daily
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Ensure you're using the correct Python version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Add any other dependencies your script requires

    - name: Run the script to update JSON files
      run: |
        python historical_matching_aspects.py  # Adjust the path if necessary

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add historical_matching_aspects_part_*.json historical_matching_aspects_index.json
        git commit -m "Auto-update historical matching aspects JSON files"
        git push origin main
